<?php

namespace AcmeNewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * Get one published News by id
     *
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findPublishedById($id)
    {
         return $this->createQueryBuilder('n')
             ->where('n.id = :id')
             ->andWhere("n.published = true")
             ->setMaxResults(1)
             ->setParameter('id', $id)
             ->getQuery()
             ->getOneOrNullResult()
        ;
    }
}
