<?php

namespace AcmeNewsBundle\Repository;

use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * Get one published News by id
     *
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findPublishedById($id)
    {
         return $this->createQueryBuilder('n')
             ->where('n.id = :id')
             ->andWhere('n.published = true')
             ->setMaxResults(1)
             ->setParameter('id', $id)
             ->getQuery()
             ->getOneOrNullResult()
        ;
    }

    /**
     * @param $id
     * @param int $count
     * @return array
     */
    public function findMoreById($id, $count = 5)
    {
        if ($count <= 0) {
            throw new InvalidArgumentException('Count should be 1 or more');
        }

        return $this->createQueryBuilder('n')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->where('n.id <> :id')
            ->andWhere('n.published = true')
            ->setParameter('id', $id)
            ->setMaxResults($count)
            ->getQuery()
            ->getResult()
        ;
    }
}
